AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild Project for WambdaInitProject CSR001 Frontend (S3 Deployment)'

Parameters:
  ProjectName:
    Type: String
    Default: build-wambda-csr001-frontend
    Description: CodeBuild project name

  GitHubOwner:
    Type: String
    Default: h-akira
    Description: GitHub repository owner

  GitHubRepo:
    Type: String
    Default: WambdaInitProject_CSR001_Frontend
    Description: GitHub repository name

  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to build

  CodeStarConnectionArn:
    Type: String
    Description: CodeStar Connection ARN for GitHub
    # Example: arn:aws:codeconnections:ap-northeast-1:XXXXXXXXXXXX:connection/xxx

  S3BucketName:
    Type: String
    Description: S3 bucket name for frontend deployment
    # Example: s3-wambda-csr001-contents

  InfraMainStackName:
    Type: String
    Default: stack-wambda-csr001-infra-main
    Description: Infrastructure main stack name (for CloudFront Distribution ID lookup)

Resources:
  # CodeConnections Managed Policy
  CodeConnectionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'CodeBuildCodeConnectionsPolicy-${ProjectName}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codestar-connections:GetConnectionToken
              - codestar-connections:GetConnection
              - codeconnections:GetConnectionToken
              - codeconnections:GetConnection
              - codeconnections:UseConnection
            Resource: !Ref CodeStarConnectionArn

  # IAM Role for CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'codebuild-${ProjectName}-service-role'
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref CodeConnectionsPolicy

  # CloudWatch Logs Policy
  CloudWatchLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudWatchLogsPolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}'
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*'

  # CodeBuild Reports Policy
  CodeBuildReportsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeBuildReportsPolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
            Resource:
              - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${ProjectName}-*'

  # S3 Deployment Policy
  S3DeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3DeploymentPolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3FrontendDeploy
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:
              - !Sub 'arn:aws:s3:::${S3BucketName}'
              - !Sub 'arn:aws:s3:::${S3BucketName}/*'

  # CloudFront Invalidation Policy
  CloudFrontInvalidationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudFrontInvalidationPolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudFormationDescribeStacks
            Effect: Allow
            Action:
              - cloudformation:DescribeStacks
            Resource:
              - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${InfraMainStackName}/*'
          - Sid: CloudFrontInvalidation
            Effect: Allow
            Action:
              - cloudfront:CreateInvalidation
            Resource:
              - !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/*'

  # CodeBuild Project
  FrontendProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value: !Ref S3BucketName
            Type: PLAINTEXT
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/${GitHubOwner}/${GitHubRepo}.git'
        BuildSpec: buildspec.yml
      SourceVersion: !Sub 'refs/heads/${GitHubBranch}'
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Sub '^refs/heads/${GitHubBranch}$'
      Tags:
        - Key: Name
          Value: codebuild-csr001-frontend
        - Key: Environment
          Value: production

Outputs:
  ProjectName:
    Description: CodeBuild Project Name
    Value: !Ref FrontendProject
    Export:
      Name: !Sub '${AWS::StackName}-ProjectName'

  ProjectArn:
    Description: CodeBuild Project ARN
    Value: !GetAtt FrontendProject.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ProjectArn'

  ServiceRoleArn:
    Description: CodeBuild Service Role ARN
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ServiceRoleArn'
