AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild Project for WambdaInitProject CSR001 Backend (SAM Deployment)'

Parameters:
  ProjectName:
    Type: String
    Default: build-wambda-csr001-backend
    Description: CodeBuild project name

  GitHubOwner:
    Type: String
    Default: h-akira
    Description: GitHub repository owner

  GitHubRepo:
    Type: String
    Default: WambdaInitProject_CSR001_Backend
    Description: GitHub repository name

  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to build

  CodeStarConnectionArn:
    Type: String
    Description: CodeStar Connection ARN for GitHub
    # Example: arn:aws:codeconnections:ap-northeast-1:XXXXXXXXXXXX:connection/xxx

Resources:
  # CodeConnections Managed Policy
  CodeConnectionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'CodeBuildCodeConnectionsPolicy-${ProjectName}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codestar-connections:GetConnectionToken
              - codestar-connections:GetConnection
              - codeconnections:GetConnectionToken
              - codeconnections:GetConnection
              - codeconnections:UseConnection
            Resource: !Ref CodeStarConnectionArn

  # IAM Role for CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'codebuild-${ProjectName}-service-role'
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref CodeConnectionsPolicy

  # CloudWatch Logs Policy
  CloudWatchLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudWatchLogsPolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudWatchLogsBasic
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}'
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*'
          - Sid: CloudWatchLogsSAM
            Effect: Allow
            Action:
              - logs:DescribeLogGroups
              - logs:CreateLogGroup
              - logs:DeleteLogGroup
              - logs:PutRetentionPolicy
              - logs:DeleteRetentionPolicy
              - logs:TagLogGroup
              - logs:UntagLogGroup
              - logs:DescribeResourcePolicies
              - logs:DescribeIndexPolicies
              - logs:ListTagsForResource
            Resource: '*'

  # CodeBuild Reports Policy
  CodeBuildReportsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeBuildReportsPolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
            Resource:
              - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${ProjectName}-*'

  # SAM Deployment Policy
  SAMDeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SAMDeploymentPolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudFormationTemplate
            Effect: Allow
            Action:
              - cloudformation:CreateChangeSet
            Resource:
              - !Sub 'arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31'
          - Sid: CloudFormationStack
            Effect: Allow
            Action:
              - cloudformation:CreateChangeSet
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeChangeSet
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStacks
              - cloudformation:ExecuteChangeSet
              - cloudformation:GetTemplateSummary
              - cloudformation:ListStackResources
              - cloudformation:UpdateStack
            Resource:
              - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*'
          - Sid: ApplicationInsights
            Effect: Allow
            Action:
              - applicationinsights:DescribeApplication
              - applicationinsights:CreateApplication
              - applicationinsights:DeleteApplication
            Resource: '*'
          - Sid: ResourceGroups
            Effect: Allow
            Action:
              - resource-groups:CreateGroup
              - resource-groups:DeleteGroup
              - resource-groups:GetGroup
              - resource-groups:GetTags
            Resource: '*'
          - Sid: S3SAMBucket
            Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:PutBucketCORS
              - s3:DeleteBucket
              - s3:Get*
              - s3:PutBucketPublicAccessBlock
              - s3:PutBucketPolicy
              - s3:PutBucketTagging
              - s3:PutBucketVersioning
              - s3:PutBucketEncryption
              - s3:PutEncryptionConfiguration
            Resource: '*'
          - Sid: Lambda
            Effect: Allow
            Action:
              - lambda:AddPermission
              - lambda:CreateFunction
              - lambda:DeleteFunction
              - lambda:GetFunction
              - lambda:GetFunctionConfiguration
              - lambda:GetFunctionRecursionConfig
              - lambda:GetFunctionCodeSigningConfig
              - lambda:GetRuntimeManagementConfig
              - lambda:InvokeFunction
              - lambda:ListTags
              - lambda:RemovePermission
              - lambda:TagResource
              - lambda:UntagResource
              - lambda:UpdateFunctionCode
              - lambda:UpdateFunctionConfiguration
              - lambda:PublishLayerVersion
              - lambda:DeleteLayerVersion
              - lambda:GetLayerVersion
            Resource:
              - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*'
              - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:*'
          - Sid: IAM
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:AttachRolePolicy
              - iam:DeleteRole
              - iam:DetachRolePolicy
              - iam:GetRole
              - iam:TagRole
              - iam:DeleteRolePolicy
              - iam:PutRolePolicy
              - iam:GetRolePolicy
              - iam:ListAttachedRolePolicies
              - iam:ListRolePolicies
              - iam:CreateServiceLinkedRole
            Resource:
              - !Sub 'arn:aws:iam::${AWS::AccountId}:role/*'
          - Sid: IAMPassRole
            Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - !Sub 'arn:aws:iam::${AWS::AccountId}:role/*'
            Condition:
              StringEquals:
                iam:PassedToService:
                  - lambda.amazonaws.com
                  - apigateway.amazonaws.com
          - Sid: APIGateway
            Effect: Allow
            Action:
              - apigateway:DELETE
              - apigateway:GET
              - apigateway:PATCH
              - apigateway:POST
              - apigateway:PUT
            Resource:
              - !Sub 'arn:aws:apigateway:${AWS::Region}:*:*'
          - Sid: SSMParameterStore
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'

  # CodeBuild Project
  BackendProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/${GitHubOwner}/${GitHubRepo}.git'
        BuildSpec: buildspec.yml
      SourceVersion: !Sub 'refs/heads/${GitHubBranch}'
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Sub '^refs/heads/${GitHubBranch}$'
      Tags:
        - Key: Name
          Value: codebuild-csr001-backend
        - Key: Environment
          Value: production

Outputs:
  ProjectName:
    Description: CodeBuild Project Name
    Value: !Ref BackendProject
    Export:
      Name: !Sub '${AWS::StackName}-ProjectName'

  ProjectArn:
    Description: CodeBuild Project ARN
    Value: !GetAtt BackendProject.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ProjectArn'

  ServiceRoleArn:
    Description: CodeBuild Service Role ARN
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ServiceRoleArn'
